### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by YasserHassan** [kartik-v/yii2-dynagrid#71]
I've started receiving the following error recently after running `composer update`. Nothing new was installed since the last successful update.
```
kartik-v/yii2-dynagrid dev-master requires kartik-v/yii2-widget-select2 ~2.0 -> no matching package found.
```
At one time the message was
```
kartik-v/yii2-dynagrid dev-master requires kartik-v/yii2-sortable ~1.2 -> no matching package found.
```
but the consistent one is the first.

**Comment by kartik-v** [comment]
Refer #67. The extension has now included version dependencies to ensure developers can build their application dependency right.

You must set valid dependencies in your app composer.json now so that proper extension versions are picked up.

For example, if you do not care much about the dependency you can maybe include the following line in your `require` section of the composer.json

```js
"kartik-v/yii2-dynagrid": "@dev"
```
