### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by evgenmil** [kartik-v/yii2-dynagrid#88]
Hi,
When paging dynaGrid, errors appear in the console:
![screenshot - 30_07](https://cloud.githubusercontent.com/assets/6258440/8983415/f6a8d0d6-36eb-11e5-98a9-cd32fe787c13.png)
What could be the reason?
Thanks.

**Comment by philippfrenzel** [comment]
have the same :( any updates on that?

https://github.com/kartik-v/yii2-grid/issues/349

**Comment by kartik-v** [comment]
The reason is - you do not have the latest release of **yii2-dynagrid** extension OR you have not updated packages via composer OR probably you've manually copied the files.

To test install a fresh app - and install the extension via composer and check.

**Comment by philippfrenzel** [comment]
I actually use "*" as version and i cleared composer cache and web assets folder... still having this issue. cleaned browser cache too

**Comment by kartik-v** [comment]
Had [updated about the new release tag for v1.4.4](https://github.com/kartik-v/yii2-dynagrid/issues/65#issuecomment-127648106) in #65.

You may need to check if you are running the latest extension code - do the usual stuff of clearing cache/web runtime assets (since you may be using stale old javascript).

**Comment by philippfrenzel** [comment]
hi, changing the version tag to 1.4.4 and cleaning all, fixed it... thanks for your support!
